name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: go test -race ./...

      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": ["feature", "enhancement", "feat"]
                },
                {
                  "title": "## 🐛 Fixes",
                  "labels": ["fix", "bug"]
                },
                {
                  "title": "## 📚 Documentation",
                  "labels": ["documentation", "docs"]
                },
                {
                  "title": "## 🧰 Maintenance",
                  "labels": ["chore", "refactor", "test", "ci"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for different platforms
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/kv-linux-amd64 ./cmd/kv
          GOOS=darwin GOARCH=amd64 go build -o dist/kv-darwin-amd64 ./cmd/kv
          GOOS=windows GOARCH=amd64 go build -o dist/kv-windows-amd64.exe ./cmd/kv

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
            dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Go Package Registry
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/abdullahkabakk/kv@${{ github.ref_name }}
