name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      discussions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: go test -race ./...

      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": ["feat", "feature", "enhancement"]
                },
                {
                  "title": "## 🐛 Bug Fixes",
                  "labels": ["fix", "bug"]
                },
                {
                  "title": "## 📚 Documentation",
                  "labels": ["docs", "documentation"]
                },
                {
                  "title": "## 🧹 Chores",
                  "labels": ["chore", "ci", "refactor", "test"]
                }
              ],
              "exclude_labels": ["skip-changelog"],
              "include_commit_body": false,
              "group_by_label": true
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Previous Release
        run: |
          # Delete the GitHub Release
          gh release delete "${{ github.ref_name }}" --yes || true

          # Delete the Git tag (local and remote)
          git tag -d "${{ github.ref_name }}" || true
          git push origin ":refs/tags/${{ github.ref_name }}" || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          generate_release_notes: false
          discussion_category_name: "Announcements"
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Go Package Registry
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/abdullahkabakk/kv@${{ github.ref_name }}
